### PR TITLE
Add event to track MongoDB and Redis commit execution time

### PR DESCRIPTION
**Pull request by DaNautilus**

### CODE REVIEW

**Comment by nanov** [comment]
@adrai any idea why apt-get fails?

**Comment by adrai** [comment]
@nanov I temporarily disabled the elasticsearch tests... can you join slack?

**Comment by adrai** [comment]
I have another idea...

**Comment by nanov** [comment]
@DaNautilus Can you explain the purpose of this commit as a whole, on a first glance it seems to complicate rather simple procedures, and aimed at a very specific ( your ) usecase / need.

It seems that the same that same effect ( and even more ) can be achieved by patching the collection models ( or it's prototype depending on the need ).

**Comment by DaNautilus** [comment]
> @DaNautilus Can you explain the purpose of this commit as a whole, on a first glance it seems to complicate rather simple procedures, and aimed at a very specific ( your ) usecase / need.
> 
> It seems that the same that same effect ( and even more ) can be achieved by patching the collection models ( or it's prototype depending on the need ).

@adrai had a better approach with his PR https://github.com/adrai/node-viewmodel/pull/70/. Therefore I close this

**Pull request closed without merging**
