### PR TITLE
Support mongo atomic operators

### PR DESCRIPTION
**Pull request by OrH**
Mongo new version throwing "TypeError: Update document requires atomic operators"

### CODE REVIEW

**Comment by adrai** [comment]
@OrH Can you add more information?
Is this because if the mongodb driver or because of mongodb itself?
Any releasenotes about this?

**Comment by OrH** [comment]
Hey @adrai , sorry for not writing more information.

About a month ago, mongodb node driver version 3.6 was released and they changed/fixed something (I think it's related to this: https://jira.mongodb.org/browse/NODE-2660) that caused the following error to be thrown when the lib's mongo driver used the `bulkWrite` method with the update operation:
```
TypeError: Update document requires atomic operators
      at UnorderedBulkOperation.raw (/usr/local/src/node_modules/mongodb/lib/bulk/common.js:976:15)
      at BulkWriteOperation.execute (/usr/local/src/node_modules/mongodb/lib/operations/bulk_write.js:47:14)
      at executeOperation (/usr/local/src/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
      at Collection.bulkWrite (/usr/local/src/node_modules/mongodb/lib/collection.js:618:10)
      at Object.bulkCommit (/usr/local/src/node_modules/viewmodel/lib/databases/mongodb.js:309:21)
      at bulkCommit (/usr/local/src/node_modules/cqrs-eventdenormalizer/lib/definitions/collection.js:510:23)
      at /usr/local/src/node_modules/cqrs-eventdenormalizer/lib/definitions/collection.js:527:18
      at /usr/local/src/node_modules/cqrs-eventdenormalizer/node_modules/async/lib/async.js:718:13
      at Immediate.iterate (/usr/local/src/node_modules/cqrs-eventdenormalizer/node_modules/async/lib/async.js:262:13)
      at processImmediate (internal/timers.js:456:21)
error: TypeError: Update document requires atomic operators
```

So adding the operator `$set` for the update, in this case, fixes it.
I hope it's clear enough =]

**Comment by adrai** [comment]
thx, included in v1.11.2

**Comment by OrH** [comment]
Thank you! 🙏

**Pull request merged**
