### PR TITLE
Fix options indexes for mongodb

### PR DESCRIPTION
**Pull request by tommiii**
the old code was deleting the options making that object always empty

### CODE REVIEW

**Comment by tommiii** [comment]
@adrai  is it possible to get it closed and release it in all the related repos?

**Comment by adrai** [comment]
Oh, sorry, have not seen the PR.
@nanov can you look at it?

**Comment by nanov** [comment]
Sorry, have missed it. Will review and release in a few hours!

**Comment by nanov** [comment]
Landed in v1.10.11, thank you!

**Comment by tommiii** [comment]
Thank you too!

**Pull request merged**
